services:
    # PHP
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        volumes:
            - .:/app

    # Serveur web
    nginx:
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - ./:/app
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    # Base de données
    db:
        image: mysql:8
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: memory
            MYSQL_USER: user
            MYSQL_PASSWORD: password
