# On se base sur l'image Docker de PHP 8 existante
FROM php:8-fpm

# On rajoute quelques extensions
RUN apt-get update && apt-get install -y
RUN apt-get install -y --no-install-recommends \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        libpq-dev \
        nano \
    && docker-php-ext-install \
        zip \
        intl \
        pdo \
        pdo_mysql \
        opcache

# On installe composer
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer

# On copie le projet
COPY . /app

# On copie le fichier d'environnement de production
COPY .env.prod /app/.env

# On défini le répertoire par défaut du container
WORKDIR /app

# On installe paquets composers (sauf ceux de dev)
RUN composer install --no-dev --optimize-autoloader

# On compile les variables d'environnement de production nécessaire à Symfony
RUN composer dump-env prod

# On vide le cache Symfony
RUN php bin/console cache:clear

#
ENTRYPOINT docker/deploy.sh